default: &default
  adapter: postgis
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'dawarich_development' %>
  queue:
    <<: *default
    database: <%= ENV['QUEUE_DATABASE_NAME'] || 'dawarich_development_queue' %>
    password: <%= ENV['QUEUE_DATABASE_PASSWORD'] %>
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: <%= ENV['CACHE_DATABASE_NAME'] || 'dawarich_development_cache' %>
    password: <%= ENV['CACHE_DATABASE_PASSWORD'] %>
    migrations_paths: db/cache_migrate

test:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'dawarich_test' %>

production:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'dawarich_production' %>
  queue:
    <<: *default
    database: <%= ENV['QUEUE_DATABASE_NAME'] || 'dawarich_production_queue' %>
    password: <%= ENV['QUEUE_DATABASE_PASSWORD'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['CABLE_DATABASE_NAME'] || 'dawarich_production_cable' %>
    password: <%= ENV['CABLE_DATABASE_PASSWORD'] %>
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: <%= ENV['CACHE_DATABASE_NAME'] || 'dawarich_production_cache' %>
    password: <%= ENV['CACHE_DATABASE_PASSWORD'] %>
    migrations_paths: db/cache_migrate

staging:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'dawarich_staging' %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
  cache:
    <<: *default
    database: <%= ENV['CACHE_DATABASE_NAME'] || 'dawarich_staging_cache' %>
    password: <%= ENV['CACHE_DATABASE_PASSWORD'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV['QUEUE_DATABASE_NAME'] || 'dawarich_staging_queue' %>
    password: <%= ENV['QUEUE_DATABASE_PASSWORD'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['CABLE_DATABASE_NAME'] || 'dawarich_staging_cable' %>
    password: <%= ENV['CABLE_DATABASE_PASSWORD'] %>
    migrations_paths: db/cable_migrate
