---
:concurrency: <%= ENV.fetch("BACKGROUND_PROCESSING_CONCURRENCY", 10) %>
:queues:
  - points
  - default
  - imports
  - exports
  - stats
  - trips
  - tracks
  - reverse_geocoding
  - visit_suggesting
  - places
